Repository mauroalderete/gcode-core, pull requests merged in 2022-08, with the labels that each got.

#63 62 improve and define incremental method of versioning and changelog
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/labels-test.yml
  .github/workflows/versioning.yml
Labels: fix, config

#64 59 fix misspell reported by goreportcardcom
  block/gcodeblock/gcodeblock.go
  block/gcodeblock/gcodeblock_config.go
  block/gcodeblock/gcodeblock_test.go
  gcode/addressablegcode/addressable_gcode.go
  gcode/gcode.go
Labels: fix

#65 60 fix performance of the examples of block and gcodeblock packages
  block/example_test.go
  block/gcodeblock/example_test.go
Labels: fix

#66 doc: add goreportcard badge
  README.md
Labels: fix, documentation

#67 remove type of change section
  .github/pull_request_template.md
Labels: fix, config

#68 Add a Gitter chat badge to README.md
  README.md
Labels: fix, documentation
